import React,{useEffect,useMemo,useState} from 'react';import {Camera,Radio,ShieldAlert,UploadCloud} from 'lucide-react';import {io} from 'socket.io-client';
const API=import.meta.env.VITE_API_URL||'';
export default function App(){const [file,setFile]=useState(null);const [preview,setPreview]=useState('');const [result,setResult]=useState(null);const [events,setEvents]=useState([]);const [busy,setBusy]=useState(false);const [err,setErr]=useState('');
 const load=()=>fetch(`${API}/api/events`).then(r=>r.json()).then(setEvents).catch(()=>{});useEffect(()=>{load();const s=io(API||window.location.origin);s.on('vision:event',ev=>setEvents(x=>[ev,...x].slice(0,30)));return()=>s.close()},[]);
 async function run(){if(!file)return;setBusy(true);setErr('');try{const fd=new FormData();fd.append('image',file);const r=await fetch(`${API}/api/detect`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Detection failed');setResult(d)}catch(e){setErr(e.message)}finally{setBusy(false)}}
 const total=useMemo(()=>events.reduce((a,e)=>a+(e.total||0),0),[events]);const alerts=events.filter(e=>e.alert).length;const latest=events[0];
 return <div className="shell"><div className="topbar"><div className="brand"><span className="dot"/>VisionTrack AI</div><span className="badge"><Radio size={12}/> real-time events</span></div><div className="hero"><div className="panel"><h1>Computer vision that behaves like a product.</h1><p className="sub">Upload an image, run YOLO inference, persist detections when MongoDB is configured, and broadcast new events live to connected dashboards with Socket.IO.</p><div className="row"><span className="tag">YOLO</span><span className="tag">FastAPI</span><span className="tag">MERN</span><span className="tag">Socket.IO</span><span className="tag">Deployable</span></div></div><div className="panel"><p className="section-title">Live telemetry</p><div className="kpis"><div className="kpi"><b>{events.length}</b><span>processed images</span></div><div className="kpi"><b>{total}</b><span>objects detected</span></div><div className="kpi"><b>{alerts}</b><span>rule alerts</span></div></div></div></div>
 <div className="grid"><div className="panel"><p className="section-title"><UploadCloud size={15}/> Vision inference</p><div className="field"><label>Image</label><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];setFile(f);setPreview(f?URL.createObjectURL(f):'');setResult(null)}}/></div><button className="btn" onClick={run} disabled={!file||busy}><Camera size={16}/>{busy?'Detecting…':'Run detection'}</button>{err&&<p className="alert">{err}</p>}<div style={{marginTop:18}}>{preview&&<div style={{position:'relative',borderRadius:14,overflow:'hidden',border:'1px solid #183447'}}><img src={preview} alt="preview" style={{width:'100%',display:'block'}}/>{result?.width&&<svg viewBox={`0 0 ${result.width} ${result.height}`} style={{position:'absolute',inset:0,width:'100%',height:'100%'}}>{result.detections?.map((d,i)=><g key={i}><rect x={d.box[0]} y={d.box[1]} width={d.box[2]-d.box[0]} height={d.box[3]-d.box[1]} fill="none" stroke="#75e6ff" strokeWidth="3"/><text x={d.box[0]+4} y={Math.max(18,d.box[1]-5)} fill="#75e6ff" fontSize="18">{d.label} {(d.confidence*100).toFixed(0)}%</text></g>)}</svg>}</div>}{latest?<><h3>{latest.fileName}</h3><div>{Object.entries(latest.counts||{}).map(([k,v])=><span className="tag" key={k}>{k}: {v}</span>)}</div>{latest.alert&&<p className="alert"><ShieldAlert size={15}/> Demo policy triggered: 2+ people detected.</p>}</>:<p className="muted">No detections yet.</p>}</div></div>
 <div className="panel"><p className="section-title">Detection stream</p><div className="list">{events.slice(0,10).map(e=><div className="item" key={e._id}><div className="row"><b>{e.fileName}</b>{e.alert&&<span className="badge">ALERT</span>}</div><div className="muted">{e.total} objects • {new Date(e.createdAt).toLocaleString()}</div></div>)}</div></div></div><div className="footer">Production extension: RTSP streams, tracking, zones, custom classes, alert routing and GPU batch inference.</div></div>}
