import 'dotenv/config';import express from 'express';import cors from 'cors';import mongoose from 'mongoose';import multer from 'multer';import {createServer} from 'http';import {Server} from 'socket.io';
const app=express();app.use(cors());app.use(express.json());const http=createServer(app);const io=new Server(http,{cors:{origin:'*'}});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024}});const AI_URL=process.env.AI_URL||'http://localhost:8000';
await mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/visiontrack').catch(e=>console.warn(e.message));
const Event=mongoose.model('VisionEvent',new mongoose.Schema({fileName:String,width:Number,height:Number,total:Number,counts:Object,detections:Array,alert:Boolean,createdAt:{type:Date,default:Date.now}}));
app.get('/api/health',(q,s)=>s.json({ok:true,service:'visiontrack-api'}));
app.post('/api/detect',upload.single('image'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'image is required'});const fd=new FormData();fd.append('file',new Blob([req.file.buffer],{type:req.file.mimetype}),req.file.originalname);const r=await fetch(`${AI_URL}/detect`,{method:'POST',body:fd});const a=await r.json();if(!r.ok)throw new Error(a.detail||'AI detection failed');const alert=(a.counts?.person||0)>=2;const ev=await Event.create({fileName:req.file.originalname,width:a.width,height:a.height,total:a.total,counts:a.counts,detections:a.detections,alert});io.emit('vision:event',ev);res.json(ev)}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/events',async(q,s)=>s.json(await Event.find().sort({createdAt:-1}).limit(30)));
app.get('/api/analytics',async(q,s)=>{const ev=await Event.find().sort({createdAt:-1}).limit(200);const counts={};for(const e of ev)for(const[k,v]of Object.entries(e.counts||{}))counts[k]=(counts[k]||0)+v;s.json({events:ev.length,alerts:ev.filter(x=>x.alert).length,objectTotals:counts})});
io.on('connection',s=>console.log('dashboard connected',s.id));http.listen(process.env.PORT||5000,()=>console.log('VisionTrack API running'));
